USE [master]
GO
/****** Object:  Database [BookAdviser]    Script Date: 18.1.2017 16:11:44 ******/
CREATE DATABASE [BookAdviser]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BookAdviser', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookAdviser.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BookAdviser_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\BookAdviser_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [BookAdviser] SET COMPATIBILITY_LEVEL = 110
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BookAdviser].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [BookAdviser] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [BookAdviser] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [BookAdviser] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [BookAdviser] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [BookAdviser] SET ARITHABORT OFF 
GO
ALTER DATABASE [BookAdviser] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [BookAdviser] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [BookAdviser] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [BookAdviser] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [BookAdviser] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [BookAdviser] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [BookAdviser] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [BookAdviser] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [BookAdviser] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [BookAdviser] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [BookAdviser] SET  DISABLE_BROKER 
GO
ALTER DATABASE [BookAdviser] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [BookAdviser] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [BookAdviser] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [BookAdviser] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [BookAdviser] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [BookAdviser] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [BookAdviser] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [BookAdviser] SET RECOVERY FULL 
GO
ALTER DATABASE [BookAdviser] SET  MULTI_USER 
GO
ALTER DATABASE [BookAdviser] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [BookAdviser] SET DB_CHAINING OFF 
GO
ALTER DATABASE [BookAdviser] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [BookAdviser] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
EXEC sys.sp_db_vardecimal_storage_format N'BookAdviser', N'ON'
GO
USE [BookAdviser]
GO
/****** Object:  Table [dbo].[Author]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Author](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Author] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Book]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Book](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](250) NOT NULL,
	[AuthorID] [int] NOT NULL,
	[PublisherID] [int] NOT NULL,
	[Abstract] [nvarchar](max) NULL,
	[LanguageID] [char](2) NULL,
	[TranslatorID] [int] NULL,
	[PublishYear] [int] NULL,
	[ISBN] [nvarchar](20) NULL,
	[Price] [decimal](6, 2) NULL,
 CONSTRAINT [PK_Book] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[Language]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[Language](
	[ID] [char](2) NOT NULL,
	[Name] [nvarchar](50) NULL,
 CONSTRAINT [PK_Language] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[List]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[List](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](250) NULL,
	[UserID] [int] NULL,
 CONSTRAINT [PK_BookList] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[ListBook]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ListBook](
	[ListID] [int] NOT NULL,
	[BookID] [int] NOT NULL,
 CONSTRAINT [PK_ListBook_1] PRIMARY KEY CLUSTERED 
(
	[ListID] ASC,
	[BookID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[Publisher]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Publisher](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Publisher] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
/****** Object:  Table [dbo].[User]    Script Date: 18.1.2017 16:11:44 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[User](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [nvarchar](50) NOT NULL,
	[Password] [nvarchar](50) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
 CONSTRAINT [PK_User] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author] FOREIGN KEY([AuthorID])
REFERENCES [dbo].[Author] ([ID])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Author]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Author1] FOREIGN KEY([TranslatorID])
REFERENCES [dbo].[Author] ([ID])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Author1]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Language] FOREIGN KEY([LanguageID])
REFERENCES [dbo].[Language] ([ID])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Language]
GO
ALTER TABLE [dbo].[Book]  WITH CHECK ADD  CONSTRAINT [FK_Book_Publisher2] FOREIGN KEY([PublisherID])
REFERENCES [dbo].[Publisher] ([ID])
GO
ALTER TABLE [dbo].[Book] CHECK CONSTRAINT [FK_Book_Publisher2]
GO
ALTER TABLE [dbo].[List]  WITH CHECK ADD  CONSTRAINT [FK_List_User] FOREIGN KEY([UserID])
REFERENCES [dbo].[User] ([ID])
GO
ALTER TABLE [dbo].[List] CHECK CONSTRAINT [FK_List_User]
GO
ALTER TABLE [dbo].[ListBook]  WITH CHECK ADD  CONSTRAINT [FK_ListBook_Book] FOREIGN KEY([BookID])
REFERENCES [dbo].[Book] ([ID])
GO
ALTER TABLE [dbo].[ListBook] CHECK CONSTRAINT [FK_ListBook_Book]
GO
ALTER TABLE [dbo].[ListBook]  WITH CHECK ADD  CONSTRAINT [FK_ListBook_List] FOREIGN KEY([ListID])
REFERENCES [dbo].[List] ([ID])
GO
ALTER TABLE [dbo].[ListBook] CHECK CONSTRAINT [FK_ListBook_List]
GO
USE [master]
GO
ALTER DATABASE [BookAdviser] SET  READ_WRITE 
GO
